version: '3'
services:
  app:
    build:
      context: .
    expose:
      - 8081
    ports:
      - 8081:8081
    user: root
    command: npm run start
    environment:
      - PORT=8081
    volumes:
      - '.:/service'
      - '/service/node_modules'
  opp:
    image: weareenvoy/okta-opp-agent
    volumes:
      - './conf:/opt/OktaProvisioningAgent/conf'
