version: '3'
services:
  app:
    build:
      context: .
    expose:
      - 8080
    ports:
      - 8080:8080
    user: root
    command: npm run start
    environment:
      - PORT=8080
    volumes:
      - '.:/service'
      - '/service/node_modules'
  opp:
    image: weareenvoy/okta-opp-agent
    volumes:
      - './conf:/opt/OktaProvisioningAgent/conf'
